engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
    checks:
      SelectorFormat:
        enabled: false
  csslint:
    enabled: false
ratings:
   paths:
   - "code/app/**/*"
   - "**.scss"
   - "**.js"
   - "**.jsx"
exclude_paths:
- node_modules/**/*
- bower_components/**/*
- "prototypes/**/*"
- "code/app/node_modules/**/*"
- "code/app/bower_components/**/*"
- "code/data/node_modules/**/*"
- "code/data/**/*"
- "code/app/.eslintrc"
- "todo/**/*"
- "data/**/*"
- "wireframes/**/*"
- ".codeclimate.yml"
- "README.md"

#comment to test
